version: "3.0"
sevices:
  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    unlimits:
      memlocks:
        soft: -1
        hard: -1
    volumes:
      esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app:latest

