version: 1
formatters:
  default:
    format: '%(asctime)s - %(levelname)s - %(pathname)s : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]

