[tool.poetry]
name = "e-commerce"
version = "0.1.0"
description = ""
authors = ["Tran Viet Phuoc <phuoc.finn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"
flask-sqlalchemy = "^2.4.1"
flask-script = "^2.0.6"
flask-mail = "^0.9.1"
flask-login = "^0.5.0"
flask-migrate = "^2.5.3"
wtforms = "^2.3.1"
flask-wtf = "^0.14.3"
black = "^19.10b0"
pynvim = "^0.4.1"
blinker = "^1.4"
jedi = "^0.17.0"
psycopg2 = "^2.8.5"
email-validator = "^1.1.1"
pillow = "^7.1.2"
python-dotenv = "^0.13.0"
flask-admin = "^1.5.6"
elasticsearch = "^7.7.1"
flask-babel = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
