"""empty message

Revision ID: 07806adb20cb
Revises: b59808dc61d6
Create Date: 2020-12-21 09:51:58.650717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07806adb20cb'
down_revision = 'b59808dc61d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
