# Generated by Django 5.1.2 on 2024-10-20 08:26

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=120, verbose_name='Category name'),
                ),
                (
                    'icon',
                    models.ImageField(
                        blank=True, upload_to=products.models.category_image_path
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                (
                    'image',
                    models.ImageField(
                        blank=True, upload_to=products.models.products_image_path
                    ),
                ),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quanity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'seller',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=models.SET(
                            products.models.get_default_product_category
                        ),
                        related_name='product_list',
                        to='products.productcategory',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
